name: Deploy branch to LeafCloud
on:
  push:
    branches:
      - staging
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: 'build'
      SERVER_IP: ssh.staging.random.studio
      SERVER_PORT: 22
      SSH_USERNAME: staging-bot
      SSH_KEY: ${{ secrets.SSH_KEY }}
      TARGET_DIR: ${{ github.event.repository.name }}
    steps:
      - id: TARGET_DIR_LOWERCASE
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.event.repository.name }}
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
      - name: Build
        run: yarn build
      - name: Create folders
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ env.SSH_KEY }}
          port: 22
          script: mkdir -p /var/www/staging.random.studio/${{ steps.string.outputs.TARGET_DIR_LOWERCASE }}
      - name: Deploy preview
        uses: AEnterprise/rsync-deploy@1.0.1
        env:
          ARGS: "-e -c -r --delete"
          DEPLOY_KEY: ${{ env.SSH_KEY }}
          USERNAME: ${{ env.SSH_USERNAME }}
          FOLDER: "./${{ env.BUILD_DIR }}/"
          SERVER_DESTINATION: '/var/www/staging.random.studio/${{ steps.string.outputs.TARGET_DIR_LOWERCASE }}/'
